/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOutreachStudioRouteImport } from './routes/_app.outreach-studio'
import { Route as AppMarketIntelligenceRouteImport } from './routes/_app.market-intelligence'
import { Route as AppLeadIntelligenceRouteImport } from './routes/_app.lead-intelligence'
import { Route as AppKnowledgeHubRouteImport } from './routes/_app.knowledge-hub'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppCampaignStudioRouteImport } from './routes/_app.campaign-studio'
import { Route as AppAutomationStudioRouteImport } from './routes/_app.automation-studio'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAiCommandCenterRouteImport } from './routes/_app.ai-command-center'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachStudioRoute = AppOutreachStudioRouteImport.update({
  id: '/outreach-studio',
  path: '/outreach-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketIntelligenceRoute = AppMarketIntelligenceRouteImport.update({
  id: '/market-intelligence',
  path: '/market-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadIntelligenceRoute = AppLeadIntelligenceRouteImport.update({
  id: '/lead-intelligence',
  path: '/lead-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeHubRoute = AppKnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignStudioRoute = AppCampaignStudioRouteImport.update({
  id: '/campaign-studio',
  path: '/campaign-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationStudioRoute = AppAutomationStudioRouteImport.update({
  id: '/automation-studio',
  path: '/automation-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCommandCenterRoute = AppAiCommandCenterRouteImport.update({
  id: '/ai-command-center',
  path: '/ai-command-center',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai-command-center': typeof AppAiCommandCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation-studio': typeof AppAutomationStudioRoute
  '/campaign-studio': typeof AppCampaignStudioRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge-hub': typeof AppKnowledgeHubRoute
  '/lead-intelligence': typeof AppLeadIntelligenceRoute
  '/market-intelligence': typeof AppMarketIntelligenceRoute
  '/outreach-studio': typeof AppOutreachStudioRoute
  '/settings': typeof AppSettingsRoute
  '/workspaces': typeof AppWorkspacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai-command-center': typeof AppAiCommandCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation-studio': typeof AppAutomationStudioRoute
  '/campaign-studio': typeof AppCampaignStudioRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge-hub': typeof AppKnowledgeHubRoute
  '/lead-intelligence': typeof AppLeadIntelligenceRoute
  '/market-intelligence': typeof AppMarketIntelligenceRoute
  '/outreach-studio': typeof AppOutreachStudioRoute
  '/settings': typeof AppSettingsRoute
  '/workspaces': typeof AppWorkspacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/ai-command-center': typeof AppAiCommandCenterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/automation-studio': typeof AppAutomationStudioRoute
  '/_app/campaign-studio': typeof AppCampaignStudioRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/knowledge-hub': typeof AppKnowledgeHubRoute
  '/_app/lead-intelligence': typeof AppLeadIntelligenceRoute
  '/_app/market-intelligence': typeof AppMarketIntelligenceRoute
  '/_app/outreach-studio': typeof AppOutreachStudioRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/signup'
    | '/ai-command-center'
    | '/analytics'
    | '/automation-studio'
    | '/campaign-studio'
    | '/crm'
    | '/dashboard'
    | '/knowledge-hub'
    | '/lead-intelligence'
    | '/market-intelligence'
    | '/outreach-studio'
    | '/settings'
    | '/workspaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/signup'
    | '/ai-command-center'
    | '/analytics'
    | '/automation-studio'
    | '/campaign-studio'
    | '/crm'
    | '/dashboard'
    | '/knowledge-hub'
    | '/lead-intelligence'
    | '/market-intelligence'
    | '/outreach-studio'
    | '/settings'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/signup'
    | '/_app/ai-command-center'
    | '/_app/analytics'
    | '/_app/automation-studio'
    | '/_app/campaign-studio'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/knowledge-hub'
    | '/_app/lead-intelligence'
    | '/_app/market-intelligence'
    | '/_app/outreach-studio'
    | '/_app/settings'
    | '/_app/workspaces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach-studio': {
      id: '/_app/outreach-studio'
      path: '/outreach-studio'
      fullPath: '/outreach-studio'
      preLoaderRoute: typeof AppOutreachStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market-intelligence': {
      id: '/_app/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof AppMarketIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead-intelligence': {
      id: '/_app/lead-intelligence'
      path: '/lead-intelligence'
      fullPath: '/lead-intelligence'
      preLoaderRoute: typeof AppLeadIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-hub': {
      id: '/_app/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub'
      preLoaderRoute: typeof AppKnowledgeHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaign-studio': {
      id: '/_app/campaign-studio'
      path: '/campaign-studio'
      fullPath: '/campaign-studio'
      preLoaderRoute: typeof AppCampaignStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation-studio': {
      id: '/_app/automation-studio'
      path: '/automation-studio'
      fullPath: '/automation-studio'
      preLoaderRoute: typeof AppAutomationStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-command-center': {
      id: '/_app/ai-command-center'
      path: '/ai-command-center'
      fullPath: '/ai-command-center'
      preLoaderRoute: typeof AppAiCommandCenterRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiCommandCenterRoute: typeof AppAiCommandCenterRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationStudioRoute: typeof AppAutomationStudioRoute
  AppCampaignStudioRoute: typeof AppCampaignStudioRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKnowledgeHubRoute: typeof AppKnowledgeHubRoute
  AppLeadIntelligenceRoute: typeof AppLeadIntelligenceRoute
  AppMarketIntelligenceRoute: typeof AppMarketIntelligenceRoute
  AppOutreachStudioRoute: typeof AppOutreachStudioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiCommandCenterRoute: AppAiCommandCenterRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationStudioRoute: AppAutomationStudioRoute,
  AppCampaignStudioRoute: AppCampaignStudioRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKnowledgeHubRoute: AppKnowledgeHubRoute,
  AppLeadIntelligenceRoute: AppLeadIntelligenceRoute,
  AppMarketIntelligenceRoute: AppMarketIntelligenceRoute,
  AppOutreachStudioRoute: AppOutreachStudioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
